app/kittchen/core/api/urls.py
from django.urls import path, include
from rest_framework import routers, serializers, viewsets
# from django.contrib.auth import views
from kittchen.core.api import views

urlpatterns = [
        # path('', include(router.urls)),
        # path('', views.ApiOverview.as_view(), name='api_overview'),
        path('recipe-list/', views.RecipeListAPIView.as_view(), name='api_recipe_list'),
        path('recipe-detail/<int:pk>/', views.RecipeDetailAPIView.as_view(), name='api_recipe_detail'),

        ]

app/kittchen/core/urls.py
from django.views.generic import RedirectView
from django.urls import path

from . import views


urlpatterns = [
        path('', RedirectView.as_view(url='home/', permanent=True)),
        path('home/', views.HomeView.as_view(), name='home'),
        path('recipe/<int:pk>', views.RecipeDetailView.as_view(), name='recipe_detail'),
        path('recipe/<int:pk>/edit/', views.RecipeUpdateView.as_view(), name='recipe_edit'),
        path('recipe/<int:pk>/delete/', views.RecipeDeleteView.as_view(), name='recipe_delete'),
        path('myrecipes', views.RecipeByUserListView.as_view(), name='myrecipes'),
        path('recipe/create/', views.RecipeCreateView.as_view(), name='recipe_create'),
        path('recipe/create/<int:pk>/add/', views.RecipeAddView.as_view(), name='recipe_add'),
        path('recipe/browse/', views.RecipeBrowse.as_view(), name='recipe_browse'),
        path('category/list/', views.CategoryListView.as_view(), name='category_list'),
        path('category/create/', views.CategoryCreateView.as_view(), name='category_create'),
        path('category/<int:pk>/update/', views.CategoryUpdateView.as_view(), name='category_rename'),
        path('category/<int:pk>/delete/', views.CategoryDeleteView.as_view(), name='category_remove'),
        # path('recipe/add/<int:pk>/test', views.testView.as_view(), name='test_recipe_add_ingredients'),
        # path('testmodel/create/', views.TestModelCreateView.as_view(), name='test_model_create'),
        ]

app/kittchen/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views
# from django.contrib.auth.models import User
# from rest_framework import routers, serializers, viewsets


"""
    API
"""


# Serializers define the API representation
# class UserSerializer(serializers.HyperlinkedModelSerializer):
#     class Meta:
#         model = User
#         fields = ['url', 'username', 'email', 'is_staff']


# ViewSets define the view behavior
# class UserViewSet(viewsets.ModelViewSet):
#     queryset = User.objects.all()
#     serializer_class = UserSerializer


# Routers provide an easy way of automatically determining the URL conf
# router = routers.DefaultRouter()
# router.register(r'users', UserViewSet)


urlpatterns = [
    # ADMIN
    path('admin/', admin.site.urls),
    # CORE APP
    path('', include('kittchen.core.urls')),
    # path('', RedirectView.as_view(url='home/', permanent=True)),
    # AUTH
    # path('accounts/', include('django.contrib.auth.urls')),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    # API
    # Wire API using automatic URL routing. Additionally include login URLS for browsable API
    # path('api', include(router.urls)),
    path('api/', include('kittchen.core.api.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/kittchen/core/models.py
from django.db import models
from datetime import date, datetime
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django.core.validators import MinValueValidator

from ordered_model.models import OrderedModel


# Post
class Post(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=100, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)  # delete blogs of deleted user
    ingredients = models.ManyToManyField('Ingredient', through='IngredientTable', help_text='Input ingredients', blank=True)
    posted_at = models.DateTimeField(auto_now_add=True)
    last_edited = models.DateTimeField(auto_now=True)
    categories = models.ManyToManyField('Category', blank=True)
    cooking_time = models.PositiveIntegerField(default=10, validators=[MinValueValidator(1)])
    servings = models.PositiveIntegerField(default=4, validators=[MinValueValidator(1)])
    # body = models.TextField(max_length=1000, help_text='Recipe body', blank=True, null=True)

    def __str__(self):
        return f"{self.title} by {self.author}."

    # Return url
    def get_absolute_url(self):
        return reverse('recipe_detail', args=[str(self.id)])

    def save(self):
        self.last_edited = datetime.now()
        super().save()

    # table name in database
    class Meta:
        db_table = "posts"


class Ingredient(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name

    class Meta:
        db_table = "ingredients"


class IngredientTable(models.Model):
    ML = 'ml'
    L = 'L'
    G = 'g'
    KG = 'Kg'
    CUP = 'cup'
    TSP = 'tsp'
    TBS = 'tbsp'
    UNIT = [
            (ML, _('ml')),
            (L, _('L')),
            (G, _('g')),
            (CUP, _('cup')),
            (TSP, _('tsp')),
            (TBS, _('tbsp')),
            ]
    id = models.AutoField(primary_key=True)
    post = models.ForeignKey(Post, related_name='items', on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    unit = models.CharField(
            max_length=33,
            choices=UNIT,
            blank=True,
            )
    # store as character then make into integer
    quantity = models.DecimalField(max_digits=8, decimal_places=3)

    def __str__(self):
        try:
            return f"{self.quantity} {self.unit} of {self.ingredient} for {self.post.title}"
        except (Ingredient.DoesNotExist, Post.DoesNotExist):
            # If ingredient table is instantiated without complete fields print the following
            return f"Incomplete object IntegerTable"

    def get_units(self):
        return self.get_unit_display()

    class Meta:
        db_table = "ingredients_table"


class Direction(OrderedModel):
    id = models.AutoField(primary_key=True)
    recipe = models.ForeignKey(Post, related_name='directions', on_delete=models.CASCADE)
    body = models.CharField(max_length=100)
    order_with_respect_to = 'recipe'

    class Meta(OrderedModel.Meta):
        db_table = 'directions'

    def __str__(self):
        try:
            return f"Direction for {self.recipe.title}: {self.body}"
        except (Post.DoesNotExist):
            # If ingredient table is instantiated without complete fields print the following
            return f"Incomplete object Direction"


class Image(models.Model):
    id = models.AutoField(primary_key=True)
    recipe = models.ForeignKey(Post, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True, upload_to="images/")

    class Meta():
        db_table = 'images'

class Category(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=32)

    def __str__(self):
        return self.name

    class Meta():
        db_table = 'categories'

# class TestModel(models.Model):
#     name = models.CharField(max_length=50, unique=True)
#     image = models.ImageField(null=True, blank=True, upload_to="images/")
#     def __str__(self):
#         return self.name
# 
# 

app/kittchen/core/utils/forms.py
import re


# Source: https://github.com/philgyford/django-nested-inline-formsets-example/blob/main/publishing/utils/forms.py
def is_empty_form(form):
    """
    Considered empty if it passes validation but
    doesn't have data
    """
    if form.is_valid() and not form.cleaned_data:
        return True
    else:
        # form has errors(isn't valid) or
        # it doesn't have errors and contains data
        return False


def is_form_persisted(form):
    """
    Does model have a model instance attached and is not being added?
    """
    if form.instance and not form.instance.__state.adding:
        return True
    else:
        # Either form has no instance attached
        # or it has instance that is being added
        return False


def get_name_with_flag(string, flag=None):
    return re.findall(r"\%(\w*)\%", string)[0]


def get_id_with_flag(string, flag=None):
    return re.findall(r"-(\d*)-", string)[0]


# Returns clean name
def clean_string(name):
    return name.rstrip().capitalize()


# Return string split in dashes or underscores
def parse_form_id(string):
    return re.split('-|_', string)

# def clean_form_id(string, pattern=None):
#     pattern = "(\w+)(?=-)*" if pattern is None else pattern
#     return re.match(pattern, string).group()


# Reassign objects based on integer key
def move_to_next_if_exists(dli, key, obj):
    prevobj = dli.get(key)
    if prevobj:
        move_to_next_if_exists(dli, key+1, prevobj)
    dli.update({key: obj})


def is_formset(x):
    return hasattr(x, 'management_form')


def is_dictionary(x):
    if type(x) is dict:
        return True
    else:
        return False

app/kittchen/core/api/views.py
# REST FRAMEWORK
from rest_framework import permissions, status, generics
# from rest_framework.decorators import api_view, permission_classes
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.throttling import UserRateThrottle
from rest_framework.generics import get_object_or_404
from rest_framework import permissions

from kittchen.core.models import Post
from kittchen.core.api.pagination import ListPagination
from kittchen.core.api.serializers import (PostListSerializer,
                                  PostDetailSerializer)


# @api_view(['GET'])
# @permission_classes((permissions.AllowAny,))
# def apiOverview(request):
#     api_urls = {
#             'List': '/recipe-list/',
#             'Detail View': '/recipe-detail/<str:pk>/',
#             }
#     return Response(api_urls)


class ApiOverview(APIView):
    # throttle_classes = [UserRateThrottle]

    def get(self, request, format=None):
        content = {
                'status': 'request was premitted',
                'List': '/recipe-list/',
                'Detail View': '/recipe-detail/<str:pk>/',
                }
        return Response(content)


# class RecipeListAPIView(APIView):
class RecipeListAPIView(generics.ListAPIView):

    queryset = Post.objects.all().order_by("-id")
    serializer_class = PostListSerializer
    permission_classes = [permissions.IsAuthenticated]
    pagination_class = ListPagination
#     def get(self, request):
#         recipes = Post.objects.filter()
#         serializer = PostListSerializer(recipes, many=True)
#         return Response(serializer.data)


class RecipeDetailAPIView(generics.RetrieveAPIView):

    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer
    permission_classes = [permissions.IsAuthenticated]

#     def get_object(self, pk):
#         recipe = get_object_or_404(Post, pk=pk)
#         return recipe

#     def get(self, request, pk):
#         recipe = self.get_object(pk)
#         serializer = PostDetailSerializer(recipe)
#         return Response(serializer.data)

app/kittchen/core/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <title>{% block head_title %}{% endblock %}</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/theme.css' %}">
  </head>

  <body>
    <!-- Nav -->
    {% block navbar %}
      {% include "navbar.html" %}
    {% endblock %}
    <!-- Nav END-->

    <!-- Content -->
    <div class="container">
      </br>
      <h1>
        {% block body_title %}
        {% endblock %}
      </h1>
      {% block content %}
      {% endblock %}
    </div>
    <!-- Content END-->

    <!-- Footer -->
    {% include "footer.html" %}
    <!-- Footer END-->

    
    <!-- Scripts -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    {% block scripts %}
    {% endblock %}
    <!-- Scripts END -->
  </body>
</html>

app/kittchen/core/templates/category_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<h1>Delete Category</h1>
<p>Are you sure you want to delete this recipe?</p>
<p><strong>{{category.name}}</strong></p>
</br>
<form action="" method="POST">
  {% csrf_token }%}
  <input class="btn btn-primary" type="submit" value="Yes">
  <a href="{{ view.get_success_url }}" class="btn btn-secondary" >Cancel</a>
</form>
{% endblock %}

app/kittchen/core/templates/category_create_form.html
{% extends "base.html" %}

{% block head_title %}Create Category{% endblock %}
{% block body_title %}Create Category{% endblock %}

{% block content %}
<form action="" method="post">
  {% csrf_token %}
  {% for hidden_field in form.hidden_fields %}
    {{ hidden_field.errors }}
    {{ hidden_field }}
  {% endfor %}
  {{ form.name}}
  {% for error in form.name.errors %}
    <strong>{{error|escape}}</strong>
  {% endfor %}

  </br>
  </br>
  <input type="submit" value="Create", class="btn btn-outline-primary">
  &nbsp; &nbsp;
  <a href="{% url 'category_list' %}" class="btn btn-outline-secondary">Cancel</a>
</form>



{% endblock %}

app/kittchen/core/templates/category_list.html
{% extends "base.html" %}

{% block head_title %}Category List{% endblock %}
{% block body_title %}Categories{% endblock %}

{% block content %}
{% if user.is_staff %}
<div class="button-fields">
  <a href="{% url 'category_create'%}" class="btn btn-lg btn-link">&plus;</a>
</div>
{% endif %}
{% if category_list %}
  <ul class="no-marker">
    {% for category in category_list %}
        <li class="categories-list">
          <div class="btn-group dropdown">
            <a href="{% url 'recipe_browse' %}?filter_by={{category.name}}">{{category.name}} </a>
            {% if user.is_staff %}
              <div type="button" class="dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></div>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'category_rename' category.id %}">Rename</a>
                <a class="dropdown-item" href="{% url 'category_remove' category.id %}">Remove</a>
              </div>
            {% endif %}
          </div>
        </li>
    {% endfor %}
  </ul>
{% else %}
  <p>No categories yet.</p>
{% endif %}

{% endblock %}

app/kittchen/core/templates/category_update_form.html
{% extends "base.html" %}

{% block head_title %}Rename Category{% endblock %}
{% block body_title %}Rename Category{% endblock %}

{% block content %}
<form action="" method="post">
  {% csrf_token %}
  {% for hidden_field in form.hidden_fields %}
    {{ hidden_field.errors }}
    {{ hidden_field }}
  {% endfor %}
  {% for error in form.name.errors %}
    <strong>{{error|escape}}</strong>
  {% endfor %}
  {{ form.name}}

  </br>
  </br>
  <input type="submit" value="Update", class="btn btn-outline-primary">
  &nbsp; &nbsp;
  <a href="{% url 'category_list' %}" class="btn btn-outline-secondary">Cancel</a>
</form>



{% endblock %}

app/kittchen/core/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark " >
  <a class="navbar-brand" href={% url 'home' %}>
  <!--
    Kittchen Monster
  -->
  {% load static %}
  <img src="{% static 'core/km_logo_01_white_small.png'%}" alt="Site Logo" class="logo-image">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <!--
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
      -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'category_list'%}">Categories</a>
      </li>

      {% if user.is_authenticated %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{ user.get_username }}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'recipe_create' %}">Post recipe</a>
          <a class="dropdown-item" href="{% url 'myrecipes' %}">My recipes</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
        </div>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}?next={{ request.path }}">Log in</a>
      </li>
      {% endif %}
    </ul>
    <form action="{% url 'recipe_browse' %}" method="get" class="form-inline my-2 my-lg-0">
     <div class="form-group has-search">
        <span class="fa fa-search form-control-feedback"></span>
        <input name="pattern" type="text" class="form-control" placeholder="Search">
      </div>
    </form>

  </div>
</nav>

app/kittchen/core/templates/recipe_browse.html
{% extends "base.html" %}

{% block head_title %}Browse Recipes{% endblock %}
{% block body_title %}Browse{% endblock %}

{% block content %}

<form class="filter" action="" method="get">
  <div style="display: inline-flex;">
    {{ form.pattern }}
    {{ form.filter_by.as_hidden }}
    <input type="submit" name="" value="Submit" class="btn btn-outline-primary">
  </div>

<div id="app">
  <tag-item
    v-for="item in data_list"
    v-bind:itm="item"
    v-bind:key="item.id"
    v-bind:class="{'pill-active': item.active}"
    :key="item.id"
    v-on:submit-method="submitCategory()"
    ></tag-item>
</div>
</form>
<ul class="no-marker">
    {% for blog in recipe_list %}
    <hr class="small-margin">
      <li class="widget-container-browse">
        <a href="{{blog.get_absolute_url}}" class="latest-recipes-item">
          <div class="widget-image-square" style="background-image: url({{blog.images.first.image.url}});"></div>
          <div class="widget-info">
            <div class="widget-info-title">{{blog.title}}</div>
            <div>
            {% for tag in blog.categories.all %}
              <span class="widget-info-tags">#{{tag.name}}</span>
            {% endfor %}
            </div>
            <div>
              <span class="far fa-clock"> {{blog.cooking_time}}'</span> 
            </div>
          </div>
        </a>
      </li>
    {% endfor %}
</ul>
{% endblock %}

{% block scripts %}

<script>
  // Fix GET method
  var tagItem = {
    props: ['itm'],
    delimiters: ["[[", "]]"],
    template: `<div v-on:click="toggleActivate(itm);$emit('submit-method')" class="badge badge-pill badge-outline-primary pill-tag">
                <input type="submit" class="tag-span" :value=[[itm.text]]>
               </div>`,
  methods: {
      toggleActivate(itm) {
        itm.active = !itm.active;
      },
  }
  }

  var app = new Vue({
    el: '#app',
    delimiters: ["[[", "]]"],
    components: {
      'tag-item': tagItem,
    },
    data: {
      data_list: [
        {% for tag in filter_list %}
        { id: {{forloop.counter0}}, text: '{{tag}}', active:{% if tag.name in active_list %}true{%else%}false{%endif%} },
        {% endfor %}
      ],
      active_list: [
        {% for tag in active_list %}
        { id: {{forloop.counter0}}, text: '{{tag}}'},
        {% endfor %}
      ]
    },
  methods: {
      submitCategory () {
        filterForm = document.getElementById("id_filter_by");
        active_list = [];
        for (const dict of this.data_list){
          if (dict['active']) {
            active_list.push(dict['text'])
          }
        }
        active_list = active_list.join(' ')
        console.log(active_list)
        filterForm.value = active_list;
      },
      // Fix post
  },
})

</script>

{% endblock%}

app/kittchen/core/templates/recipe_create_form.html
{% extends "base.html" %}

{% block head_title %}Create Recipe{% endblock%}
{% block body_title %}Create Recipe {% endblock %}

{% block content %}
<p>Author: {{ user.get_username }}</p>
<form action="" method="post">
  {% for hidden_field in form.hidden_fields %}
    {{ hidden_field.errors }}
    {{ hidden_field }}
  {% endfor %}
  {% csrf_token %}

  {{ form.non_form_errors }}
  {{ form.title}}
  </br>
  <input type="submit" value="Create recipe", class="btn btn-outline-primary">
  &nbsp; &nbsp;
  <a href="{% url 'home' %}" class="btn btn-outline-secondary">Cancel</a>
</form>
{% endblock %}

app/kittchen/core/templates/recipe_list_user.html
{% extends "base.html" %}

{% block head_title %}<title>Kittchen Monster User Recipes</title>{% endblock %}
{% block body_title %}{{user.get_username}} Recipes{% endblock %}

{% block content %}
</br>
  {% if post_list %}
  <div class="widget-square-container">
    {% for recipe in post_list %}
    <a href="{{recipe.get_absolute_url}}">
      <div
        class="widget-image-square"
        style="background-image:
              linear-gradient(to bottom, rgba(37,37,37,0) 30%, rgba(37,37,37,0.3) 60%, rgba(37,37,37,1)),
              url({{recipe.images.first.image.url}});">
        <span style="position:absolute;bottom: 0;margin: .5em .5em;">{{recipe.title}}</span>
      </div>
    </a>
    {% endfor %}
  </div>
  {% else %}
    <p>No recipes submitted.</p>
  {% endif %}


{% endblock %}

app/kittchen/core/templates/test_ingredients_form.html
{% extends "base.html" %}

{% block title %}<title> Add Ingredients</title>{% endblock%}

{% block content %}
<!--
<div id="shopping-list">
  <h2>List</h2>
  <ul class="list-group">
    <span v-for="(item, index) in itemList">
      <li class="list-group-item d-flex justify-content-between align-items-center"> 
        <p v-show="!item.inEditMode">[[item.quantity]]</p>
        hello world
        <div>
          <button class="btn btn-primary">Edit</button>
          <button class="btn btn-primary">Delete</button>
        </div>
      </li>


    </span>
  </ul>
</div>
-->
<div id="shopping-list">
  <h2>Add ingredients</h2>
  <div id='component-demo'>
    <form-top></form-top>
  </div>
  <!--
  <input type="text" class="form-control" placeholder="New ingredient"
    v-model="newIngredient" @keyup.enter="addIngredient">
  -->
  <p><small><em> Number of ingredients: [[itemNum]]</em></small></p>
  </br> 
  <div class="list-group">
    <div class="list-group-item d-flex justify-content-between align-items-center" 
      v-for="(item, index) in ingredients" :key="ingredients.id" >
      <div>
        <div class="" v-if="!item.editing" @click="editIngredient(item)"> [[item.itemName]] </div>
        <input v-else class="form-control" type="text" v-model="item.itemName"
        @blur="doneEdit(item)" @keyup.enter="doneEdit(item)" @keyup.esc="cancelEdit(item)" v-focus>
      </div>
      <button class="btn btn-sm " @click="removeIngredient(index)">
        &times;
      </button>
    </div>
  </div>
  <p>{{ form.as_p}}</p>

</div>



{% endblock %}
<!--
  <p>{{unit}} {{unit.ingredienttable_set.get_unit_display}} </p>

-->
<!-- -->


{% block scripts %}
<script>

  Vue.component('form-top', {
    delimiters: ['[[', ']]'],
    props: ['text'],
    template:
    `<div class="input-group">
      <input type="text" class="form-control input-large" placeholder="New ingredient">
      <select class="custom-select" id="inputGroupSelect01">
        <option selected> </option>
        <option>unit</option>
        {% for unit in recipes%}
        <option>{{unit}}</option>
        {% endfor %}
      </select>

      <input type="text" class="form-control input-small" placeholder="Quantity">
      <button class="btn btn-outline-secondary" type="button">Ok</button>
    </div>
    `
  })
  new Vue({ el: '#component-demo', })

  var vm = new Vue({
    el: '#shopping-list',
    delimiters: ["[[", "]]"],
    data () {
      return {
        newIngredient: '',
        idForIngredient: 3,
        beforeEditCache: '',
        ingredients: [
          { 'id': 1, 'itemName': 'Apples', 'quantity': 2, 'editing': false},
          { 'id': 2, 'itemName': 'Oranges', 'quantity': 4, 'editing': false},
        ]

      }
    },
    directives: {
      focus: {
        inserted: function (el) {
          el.focus()
        }
      }
    },
    methods: {
      addIngredient() {
        if(this.newIngredient.trim().length == 0) {
          return
        }
        this.ingredients.unshift({
          id: this.idForIngredient,
          itemName: this.newIngredient,
          editing: false
        })

        this.newIngredient= '';
        this.idForIngredient++;
      },
      removeIngredient(index) {
        this.ingredients.splice(index,1)
      },
      editIngredient(item) {
        this.beforeEditCache = item.itemName
        item.editing = true
      },
      doneEdit(item) {
        if (item.itemName.trim().length == 0) {
          item.itemName = this.beforeEditCache
        }
        item.editing = false

      },
      cancelEdit(item) {
        item.itemName = this.beforeEditCache
        item.editing = false
      },

    },
    computed: {
      itemNum () {
        return this.ingredients.length
      }
    }

  });

// Define component called todo-item
</script>
{% endblock %}